package(
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"]
    ),
)

cc_library(
    name = "endian",
    hdrs = ["endian.h"],
    deps = [
    ],
)

cc_library(
    name = "utils",
    hdrs = ["utils.h"],
    srcs = ["utils.cc"],
    deps = [
    ],
)